### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by akeilox** [nathanwoulfe/McTaggart#1]
Thanks for sharing this package, interesting idea indeed.

When i try it on 7.2 install, in the console i see the path its trying to retrieve the script file has /~ after umbraco;

/umbraco/~/App_Plugins/McTaggart/lib/typeahead.bundle.min.js?umb__rnd=7.2.0-alpha.2127282376

which becomes 404 and breaks the control.

**Comment by nathanwoulfe** [comment]
No worries, thanks for logging this. Will spin up a 7.2 and check it out. 

Nathan Woulfe
Media, marketing and communications consultant

nathan@nathanw.com.au
0413 512 083

**Comment by nathanwoulfe** [comment]
Strange. I'm getting a 400 error back from the tag controller.

**Comment by akeilox** [comment]
There is a typo in my previous comment, its not 404 but 400 due to the URL, /~/ perhaps?
/umbraco/~/App_Plugins/McTaggart/lib/typeahead.bundle.min.js?umb__rnd=7.2.0-alpha.2127282376

**Comment by nathanwoulfe** [comment]
I've added a new version (1.1) to the [project on our.umbraco](https://our.umbraco.org/projects/backoffice-extensions/mctaggart-auto-tagging-for-umbraco/) - the typeahead is removed completely so the error should be gone. My 400 error was due to a lack of error handling, so that should be gone in 1.1 as well.
